# Generated by Django 4.1.7 on 2024-12-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='*', max_length=100, verbose_name='Owner'),
        ),
    ]
